const types = {
  LOG_EMAIL: 'LOG_EMAIL',
  REQUEST: 'REQUEST',
  RESPONSE: 'RESPONSE',
  EXPENSES: 'EXPENSES',
  DELETE_EXPENSE: 'DELETE_EXPENSE',
  EDIT_BTN: 'EDIT_BTN',
  EDIT_EXPENSE: 'EDIT_EXPENSE',
};

export default types;
