const SAVE_USER = 'SAVE_USER';
const SAVE_EXPENSE = 'SAVE_EXPENSE';
const SAVE_CURRENCIES_NAMES = 'SAVE_CURRENCIES_NAMES';
const DELETE_EXPENSE = 'DELETE_EXPENSE';

export { SAVE_USER, SAVE_EXPENSE, SAVE_CURRENCIES_NAMES, DELETE_EXPENSE };
